name: On Release Deleted
run-name: On Release Deleted ${{ github.event.release.tag_name }}

on:
  release:
    types:
      - deleted

jobs:
  get-info:
    name: Get Release Info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: GitHub Reference
        run: |
          echo "Ref            ${{ github.ref }}"
          echo "Ref Name       ${{ github.ref_name }}"
          echo "Ref Type       ${{ github.ref_type }}"
          echo "Ref SHA        ${{ github.sha }}"
          echo "Ref Head SHA   ${{ github.head_sha }}"
          echo "Ref Base SHA   ${{ github.base_sha }}"

      - name: Workflow Triggered
        run: |
          echo "Action ${{ github.event.action }}"

      - name: Get Release Info
        run: |
          echo "Id            ${{ github.event.release.id }}"
          echo "Name          ${{ github.event.release.tag_name }}"
          echo "HTML URL      ${{ github.event.release.html_url }}"
          echo "URL           ${{ github.event.release.url }}"
          echo "Tarball URL   ${{ github.event.release.tarball_url }}"
          echo "Zipball URL   ${{ github.event.release.zipball_url }}"
          echo "Is draft      ${{ github.event.release.draft }}"
          echo "Is prerelease ${{ github.event.release.prerelease }}"
          echo "Is published  ${{ github.event.release.published_at }}"
